#!/bin/bash

for file in arbr*.xyz; do
        name=${file##*/}
        base=${name%.xyz}
        xtb $name --opt >>  ${base}.out
	mv xtbopt.xyz ${base}opt.xyz
done
rm xtbopt.log xtbrestart xtbtopo.mol charges wbo
